enum EpsonEPOSPortType { ALL, TCP, BLUETOOTH, USB }

enum EpsonEPOSPrintLang {
  MODEL_ANK,
  MODEL_CHINESE,
  MODEL_TAIWAN,
  MODEL_KOREAN,
  MODEL_THAI,
  MODEL_SOUTHASIA
}

enum EpsonEPOSCut { CUT_FEED, CUT_NO_FEED, CUT_RESERVE }

enum EpsonEPOSTextAlign { LEFT, CENTER, RIGHT }

enum EpsonEPOSFont { FONT_A, FONT_B, DEFAULT }

enum EpsonEPOSBarcodeType {
  BARCODE_UPC_A,
  BARCODE_UPC_E,
  BARCODE_EAN13,
  BARCODE_JAN13,
  BARCODE_EAN8,
  BARCODE_JAN8,
  BARCODE_CODE39,
  BARCODE_ITF,
  BARCODE_CODABAR,
  BARCODE_CODE93,
  BARCODE_CODE128,
  BARCODE_GS1_128,
  BARCODE_GS1_DATABAR_OMNIDIRECTIONAL,
  BARCODE_GS1_DATABAR_TRUNCATED,
  BARCODE_GS1_DATABAR_LIMITED,
  BARCODE_GS1_DATABAR_EXPANDED,
}

enum EpsonEPOSHRI {
  HRI_NONE,
  HRI_ABOVE,
  HRI_BELOW,
  HRI_BOTH,
}
